{% set version = "0.7.0" %}

package:
  name: pycamhd
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/p/pycamhd/pycamhd-{{ version }}.tar.gz
  sha256: 84b3303c595a7ce5fe96debf4b273ce18a25edafccebfe5fb342b69e630ae141

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - av >=0.4.0
    - numpy
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - pycamhd

about:
  home: https://github.com/tjcrone/pycamhd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Module for interacting with OOI CamHD video data

extra:
  recipe-maintainers:
    - ocefpaf
