travis:
  secure:
    BINSTAR_TOKEN: fN0n95Ec3C0TldOVjYSB3zLrZIZRN37O4C78hun0g5GHWI5WW7CEgnmyHDHnWibRcg0XfxYFUO7eQhd5Mw6EFlArFAYejaAzJL/BYPE65SgdF+aQdkQBrTWGewgYRMHGIl/g9U1Hja3J1UfgENhzmjmjrzJICExgLWEdXc4MJvGIEdIDSONXLYnXZI0lzxeLRj0+0FHnb38DVOQt693IwBuDoM2V610BzSInOfKm+K3phO8HrRp9q3aHbCwIx/aRlXiIdgo9Ze66RDacYoE7UlpmlcgJYg/GTshKgrUgdhBckKmL6xk9uJpLV/zycoNgIyKfUTiSLvK+VmcEZwIzBdvcH0B00KHAaaEt7gpFGqH+R/dzGzpf+Y+emN7QV228Z6JmNk5rcGZvdGwIMskTOwlC4oE8vc20D4hRjk4WUkDNfF3BGRzfbzDk0bs6rfvFNRUruReXLNEZwz9iFjoNn9WM8oKKPR2SmdIsqB2qhqN5Qm1HAWQJa3bz1cChlow/QCZSAhfjJbTjqQ/DzYEt4ubrV/I9oDsLBdTzT/Q8gIQZeZM3J+/z79IHejDyiypRcQajVJpJa60Pm+4xMKtP+pDRnFfVgPr3KePqrq3AF523MZq6L+EkNvfpu2kTCqeIi3hrqpPC+kTHh1nQbdwdKnulh3eiZUt2voebLv0+PpU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
